version: "3"

services:
  eris-docs-bot:
    container_name: eris-docs-bots
    build:
      context: ./ErisDocsBot
      dockerfile: Dockerfile
    volumes:
      - ./ErisDocsBot/data:/data:z
      - ./ErisDocsBot/config.json:/app/config.json
    restart: always
    init: true
    healthcheck:
      interval: 10s
      timeout: 2s
      test: lsof -i :80 || exit 1
    hostname: eris-docs-bot.containers.local
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - default
  oceanic-bot:
    container_name: oceanic-bot
    build:
      context: ./OceanicBot
      dockerfile: Dockerfile
    volumes:
      - ./OceanicBot/data:/data:z
      - ./OceanicBot/config.jsonc:/app/config.jsonc
    restart: always
    init: true
    hostname: oceanic-bot.containers.local
    networks:
      - default
  security:
    container_name: security-bot
    build:
      context: ./Security
      dockerfile: Dockerfile
    volumes:
      - ./Security/data/bot:/data
      - ./Security/servers.jsonc:/app/servers.jsonc
    restart: always
    init: true
    hostname: security.bots.containers.local
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - default
  datamining-bot:
    container_name: datamining-bot
    build:
      context: ./DataminingBot
      dockerfile: Dockerfile
    volumes:
      - ./DataminingBot/data:/data:z
      - ./DataminingBot/config.json:/app/config.json
    restart: always
    init: true
    hostname: datamining-bot.containers.local
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - default

networks:
  default:
    name: simple-bots
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.32/28
          gateway: 172.19.3.33

volumes:
  modules: null
