  
version: "3"

services:
  eris-docs-bot:
    container_name: eris-docs-bot
    image: ghcr.io/donovandmc/eris-docs-bot
    volumes:
      - ./ErisDocsBot/data:/data:z
      - ./ErisDocsBot/config.json:/app/config.json
    restart: always
    hostname: eris-docs-bot.containers.local
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 128M
    networks:
      default:
        ipv4_address: 172.19.3.34
  oceanic-bot:
    container_name: oceanic-bot
    image: ghcr.io/oceanicjs/bot
    volumes:
      - ./OceanicBot/data:/data:z
      - ./OceanicBot/config.jsonc:/app/config.jsonc
    restart: always
    hostname: oceanic-bot.containers.local
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 128M
    networks:
      default:
        ipv4_address: 172.19.3.35
  project-manager:
    container_name: project-manager
    image: ghcr.io/donovandmc/project-manager
    volumes:
      - ./ProjectManager/data/bot:/data
      - ./ProjectManager/projects.json/bot:/app/projects.json
    restart: always
    hostname: project-manager.bots.containers.local
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 128M
    networks:
      default:
        ipv4_address: 172.19.3.36
  security:
    container_name: security-bot
    image: ghcr.io/donovandmc/security-bot
    volumes:
      - ./Security/data/bot:/data
      - ./Security/servers.jsonc:/app/servers.jsonc
    restart: always
    hostname: security.bots.containers.local
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 128M
    networks:
      default:
        ipv4_address: 172.19.3.37
  datamining-bot:
    container_name: datamining-bot
    image: ghcr.io/oceanicjs/datamining-bot
    volumes:
      - ./DataminingBot/data:/data:z
      - ./DataminingBot/config.json:/app/config.json
    restart: always
    hostname: datamining-bot.containers.local
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 128M
    networks:
      default:
        ipv4_address: 172.19.3.38

networks:
  default:
    name: simple-bots
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.32/28
          gateway: 172.19.3.33

volumes:
  modules: null
